databases:
  - name: alx_database
    plan: free
    databaseName: alx_database
    user: alx_database_user

services:
  - type: web
    plan: free
    name: setup_file
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn setup_file.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alx_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4