databases:
  - name: setup_file
    plan: free
    databaseName: setup_file
    user: cysoft

services:
  - type: web
    plan: free
    name: setup_file
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn setup_file.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: setup_filedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4