# Generated by Django 5.0.4 on 2024-08-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchpro', '0002_remove_hirewriter_status_jobstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirewriter',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='exprerience',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='hirewriter',
            name='job_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchpro.jobstatus'),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researchpro.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='doctype',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX')], max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_level',
            field=models.CharField(choices=[('nce/nd', 'NCE/ND'), ('hnd', 'HND'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate')], max_length=16),
        ),
        migrations.AlterField(
            model_name='writer',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchpro.project')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchpro.writer')),
            ],
        ),
    ]
